# Generated by Django 2.2.7 on 2019-12-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191201_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.TextField(default='your chat'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Profile'),
        ),
    ]
