# Generated by Django 2.2.7 on 2019-12-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20191202_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='create_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.Message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chats', to='chat.Participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_participant_friends_+', to='chat.Participant'),
        ),
        migrations.AlterField(
            model_name='message',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='chat.Profile'),
        ),
    ]
